apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curl-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curl-nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: curl-nginx
        image: radial/busyboxplus:curl
        command: ["sh", "-c"]
        args: ["while true; do sleep 1; done"]
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
